name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Lint with Eslint
        run: |
          bun run lint

      - name: Check code formatting
        run: |
          bun run format:check

      - name: Build
        run: |
          bun run build

      - name: Unit tests
        run: |
          bun test

      - id: semantic-release
        name: Run semantic-release
        run: |
          bunx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Storybook
        run: |
          bun run build-storybook
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Publish Storybook to Chromatic
        run: |
          bun run chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        if: ${{ steps.semantic-release.outputs.nextVer != null }}
